---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: charts-azure-iotedge
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: main
  url: ssh://git@github.com/atlasdevorg/charts-azure-iotedge