---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.0.0
    replicas: 1
    listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      #inter.broker.protocol.version: 3.0
      #log.message.format.version: 3.0
    storage:
      type: persistent-claim
      size: 5Gi
      class: local-storage
    jvmOptions: {}
    resources:
      requests:
        memory: 2500Mi
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: kafka-metrics-config.yml
          name: kafka-metrics
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: ERROR
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 5Gi
      class: local-storage
    resources:
      requests:
        memory: 1400Mi
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: zookeeper-metrics-config.yml
          name: kafka-metrics
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: ERROR
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 600Mi
    userOperator:
      resources:
        requests:
          memory: 256Mi
