apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: 2.7.0
    replicas: 1
    resources:
      requests:
        memory: 2500Mi
    jvmOptions:
      gcLoggingEnabled: false
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: ERROR
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.3"
    storage:
      type: persistent-claim
      size: 5Gi
      class: local-storage
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml

  zookeeper:
    replicas: 1
    resources:
      requests:
        memory: 1400Mi
    storage:
      type: persistent-claim
      class: local-storage
      size: 5Gi
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: ERROR
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml

  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 600Mi
    userOperator:
      resources:
        requests:
          memory: 256Mi
