apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka
resources:
  - cluster.yaml
  - kafka-metrics-config.yaml
  - kafka-metrics-svc.yaml
  - persistent-volumes.yaml
  
  - topic-input.yaml
  - topic-data.yaml
  - topic-process.yaml
  - topic-fieldrules.yaml
  - topic-entitychangedinput.yaml
  - topic-withrules.yaml
  - topic-checkreferences.yaml
  - topic-output.yaml
  - topic-entitychangedoutput.yaml
  - topic-deadletter.yaml
  - topic-imageclassification.yaml



