apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: entitychangedinput
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.bytes: 209715200