apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  releaseName: traefik
  targetNamespace: kube-system
  chart: 
    spec: 
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: "9.11.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    ports:
      mqtt:
        port: 1883
        expose: true
        exposedPort: 1883
        protocol: TCP
    logs:
      general:
        level: ERROR
    access:
      enabled: true
    ingressRoute:
      dashboard:
        enabled: false
    resources:
      requests:
        memory: 64Mi