---
apiVersion: batch/v1
kind: Job
metadata:
  name: schema-register-job
  namespace: kafka-streams
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.schema-register-jobd: glob:test-*
    fluxcd.io/tag.init: glob:test-*
  labels:
    app: schema-register-job 
spec:
  template:
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - name: schema-register-jobd
        image: sodadeveloper.azurecr.io/boost-schema-register-job:7262
        imagePullPolicy: IfNotPresent
        env:
        - name: REGISTRY_URL
          value: http://avro-schema-registry.kafka
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 16Mi
      restartPolicy: Never
  backoffLimit: 4
