apiVersion: v1
kind: ConfigMap
metadata:
  name: status-page-config
  namespace: platform-infrastructure
data:
  config.yaml: |
    alerting:
      custom:
        url: "{YOUR_WEBHOOK_HERE}"
        method: "POST"
        insecure: true
        body: |
          {
            "@type": "MessageCard",
            "@context": "https://schema.org/extensions",
            "summary": "Health Status Alert",
            "themeColor": "0075FF",
            "sections": [
              {
                "startGroup": true,
                "title": "**[ALERT_TRIGGERED_OR_RESOLVED]: [SERVICE_NAME]**",
                "activityTitle": "[ALERT_DESCRIPTION]"
              }
            ]
          }

    services:
      - name: kafka
        group: ingestion
        url: http://kafka-healthcheck.strimzi:8000/cluster
        interval: 1m
        conditions:
          - "[STATUS] == 200"
          - "[BODY].status == green"
        alerts:
          - type: custom
            enabled: true
            failure-threshold: 3
            success-threshold: 2
            send-on-resolved: true
            description: "Kafka healthcheck failed 3 times in a row. Data ingestion could be delayed until resolved."      


