apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: edge-crd
spec:
  releaseName: edge-crd
  chart:
    spec:
      chart: ./edge-kubernetes-crd
      sourceRef:
        name: charts-azure-iotedge
        namespace: flux-system
        kind: GitRepository
      version: "0.2.13.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3

